# Generated by Django 4.0.10 on 2023-05-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=100000)),
                ('published', models.DateTimeField()),
                ('category', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=150)),
                ('views', models.IntegerField(default=0)),
                ('access', models.CharField(default='public', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
            ],
        ),
    ]
