# Generated by Django 4.0.10 on 2023-05-12 00:32

from django.db import migrations, models
\

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.JSONField(default={'name': 'evans'}),
            preserve_default=False,
        ),
    ]
