# Generated by Django 4.0.10 on 2023-05-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.JSONField(default={'name': 'evans'}),
        ),
    ]
