# Generated by Django 4.0.10 on 2023-05-12 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.JSONField(default={'name': 'evans'}),
        )
    ]
