# Generated by Django 4.0.10 on 2023-05-12 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_post_data_post_created_at_post_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='attendees',
            field=models.JSONField(default={'list': []}),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='folder',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.JSONField(default={'list': []}),
        ),
        migrations.AddField(
            model_name='post',
            name='project_status',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='venue',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='venue_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='draft', max_length=150),
        ),
    ]
