# Generated by Django 4.2.1 on 2023-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_post_timestamp_post_attendees_post_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="documents",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="attendees",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="gallery",
            field=models.JSONField(default=dict),
        ),
    ]
