# Generated by Django 4.2.1 on 2023-05-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_post_documents_alter_post_attendees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(default="draft - writing", max_length=150),
        ),
    ]
