# Generated by Django 4.2.1 on 2023-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_post_excerpt_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="step",
            field=models.CharField(default="category", max_length=150),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(default="draft", max_length=150),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled", max_length=300),
        ),
    ]
