# Generated by Django 4.2.1 on 2023-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_post_step_alter_post_status_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
