# Generated by Django 4.2.1 on 2023-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="step",
            field=models.CharField(default="writing", max_length=150),
        ),
    ]
