# Generated by Django 4.2.1 on 2023-05-16 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_post_step"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="documents",
            new_name="files",
        ),
        migrations.RemoveField(
            model_name="post",
            name="gallery",
        ),
    ]
