# Generated by Django 4.2.1 on 2023-05-16 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_rename_documents_post_files_remove_post_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=300)),
                ("company", models.CharField(max_length=300)),
                ("designation", models.CharField(max_length=300)),
                ("password", models.CharField(max_length=300)),
                ("bio", models.CharField(blank=True, max_length=500)),
                ("technology", models.CharField(blank=True, max_length=300)),
                ("company_email", models.CharField(blank=True, max_length=300)),
                ("company_phone", models.CharField(blank=True, max_length=300)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("website_link", models.CharField(blank=True, max_length=300)),
                ("logo", models.CharField(blank=True, max_length=300)),
                (
                    "registration_status",
                    models.CharField(default="unregistered", max_length=150),
                ),
                (
                    "subscription_status",
                    models.CharField(default="inactive", max_length=150),
                ),
                ("subscription_category", models.CharField(blank=True, max_length=300)),
                (
                    "subscription_expiry",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="active", max_length=150)),
                ("step", models.CharField(default="writing", max_length=150)),
                ("created_by", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
