# Generated by Django 4.2.1 on 2023-05-16 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_member_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="subscription_expiry",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
