# Generated by Django 4.2.1 on 2023-05-16 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_member_subscription_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=500)),
                ("image", models.CharField(blank=True, max_length=300)),
                ("likes", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(default="active", max_length=150)),
                ("created_by", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
