# Generated by Django 4.2.1 on 2023-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_socialpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
