# Generated by Django 4.2.1 on 2023-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_socialpost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
