# Generated by Django 4.2.1 on 2023-05-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
