# Generated by Django 4.2.1 on 2023-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_search_limit_search_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="project_status",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
