# Generated by Django 4.2.1 on 2023-06-16 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kopokopo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=150)),
                ("transaction_id", models.CharField(max_length=150)),
                ("timestamp", models.CharField(max_length=150)),
                ("event", models.JSONField(default=dict)),
                ("links", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
