# Generated by Django 4.2.1 on 2023-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_administrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="role",
            field=models.CharField(default="admin", max_length=300),
        ),
    ]
