# Generated by Django 4.2.1 on 2023-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="email",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
