# Generated by Django 4.2.1 on 2023-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_payment_email_payment_name_payment_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="company",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="member",
            name="designation",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
