# Generated by Django 4.2.1 on 2023-08-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="socialpost",
            field=models.IntegerField(default=0),
        ),
    ]
