# Generated by Django 4.2.1 on 2023-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_alter_comment_socialpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="bookmarks",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="member",
            name="email_activation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="step",
            field=models.CharField(default="company", max_length=150),
        ),
    ]
