# Generated by Django 4.2.1 on 2023-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_member_bookmarks_member_email_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='user_type',
            field=models.CharField(default='administrator', max_length=150),
        ),
    ]
