# Generated by Django 4.2.1 on 2023-08-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_administrator_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to="api.administrator",
            ),
        ),
    ]
