# Generated by Django 4.2.1 on 2023-08-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_alter_administrator_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="author",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
