# Generated by Django 4.2.1 on 2023-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_member_postal_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
