# Generated by Django 4.2.1 on 2023-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0047_alter_post_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
