# Generated by Django 4.2.1 on 2023-08-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="author",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="company",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to="api.member",
            ),
        ),
    ]
