# Generated by Django 4.2.1 on 2023-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_socialpost_author_socialpost_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="user_type",
            field=models.CharField(default="member", max_length=150),
        ),
    ]
