# Generated by Django 4.2.1 on 2023-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_comment_author_comment_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="logo",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
