# Generated by Django 4.2.1 on 2023-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_alter_member_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="likes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="member",
            name="bookmarks",
            field=models.JSONField(default=dict),
        ),
    ]
