# Generated by Django 4.2.1 on 2023-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_member_likes_alter_member_bookmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="logo",
            field=models.CharField(default="default.png", max_length=300),
        ),
    ]
