# Generated by Django 4.2.1 on 2023-08-28 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_alter_member_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=300)),
                ("company", models.CharField(blank=True, max_length=300)),
                ("designation", models.CharField(blank=True, max_length=300)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("invoice_number", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(default="unpaid", max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
