# Generated by Django 4.2.1 on 2023-08-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="donation_id",
            field=models.IntegerField(default=0),
        ),
    ]
