# Generated by Django 4.2.1 on 2024-01-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_invoice_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="status",
            field=models.CharField(default="inactive", max_length=150),
        ),
    ]
